apiVersion: v1

kind: Secret

metadata:
  name: ckad-secret

data:
  # The values must be in the base64 encoded form! Use "echo -n "pwd" | base64" to encode.
  # Use "echo -n "cHdk" | base64 --decode" to decode.
  PASSWORD: cHdk
  TOKEN: M3NkbGtzZGZqM2Q5YQ==
