apiVersion: v1

kind: Pod

metadata:
  name: ckad-pod
  labels:
    type: front-end

spec:
  containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      resources: { }
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: color
                operator: In
                values:
                  - blue
