apiVersion: v1
kind: Pod
metadata:
  labels:
    run: capturing-server
  name: capturing-server
spec:
  containers:
    - image: yaskovdev/capturing-server
      name: capturing-server
  dnsPolicy: ClusterFirst
  restartPolicy: Always
