apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: capturing-server
  name: capturing-server-service
spec:
  ports:
    - port: 49160
      protocol: TCP
      targetPort: 8080
  selector:
    run: capturing-server
  type: NodePort
status:
  loadBalancer: {}
