@MediaApp_HostAddress = http://localhost:5032

GET {{MediaApp_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{MediaApp_HostAddress}}/processings/{{sessionId}}/
Accept: application/json
