apiVersion: apps/v1

kind: ReplicaSet

metadata:
  name: ckad-replica-set

spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        type: front-end

    spec:
      containers:
        - name: nginx-container
          image: nginx

  replicas: 2

  selector:
    matchLabels:
      type: front-end
