CREATE TABLE role (
  id   INTEGER PRIMARY KEY,
  name VARCHAR(40)
);

CREATE TABLE privilege (
  id      INTEGER PRIMARY KEY,
  role_id INTEGER REFERENCES role,
  name    VARCHAR(40)
);

INSERT INTO role VALUES (2000, 'ROLE_ADMIN');
INSERT INTO privilege VALUES (5000, 2000, 'PRIVILEGE_CREATE_USER');
INSERT INTO privilege VALUES (5001, 2000, 'PRIVILEGE_DELETE_USER');
