apiVersion: v1

kind: Pod

metadata:
  name: ckad-pod
  labels:
    type: front-end

spec:
  containers:
    - name: nginx-container
      image: nginx
  serviceAccount: jenkins # if you want to use not default sa (default is very limited, it can only query basic k8s API)

# "automountServiceAccountToken: false" to not mount service account to the pod